{% set version = "2.5.0" %}
{% set buildnumber = 0 %}

package:
    name: mkl-service
    version: {{ version }}

source:
    path: ..

build:
    number: {{ buildnumber }}
    ignore_run_exports:
      - blas
      - mkl-service

requirements:
    build:
      - {{ compiler('c') }}
    host:
      - python
      - setuptools >=77
      - mkl-devel
      - cython
    run:
      - python
      - mkl

test:
    requires:
      - pytest
    imports:
      - mkl
    commands:
      - pytest -vv --pyargs mkl

about:
    home: http://github.com/IntelPython/mkl-service
    license: BSD-3-Clause
    license_file: LICENSE.txt
    license_family: BSD
    description:
        Intel(R) OneAPI Math Kernel Library (OneMKL) support functions are
        subdivided into the following groups according to their purpose, such as
            Version Information
            Threading Control
            Timing
            Memory Management
            Conditional Numerical Reproducibility Control
            Miscellaneous
    summary: Python hooks for Intel(R) OneMKL runtime control settings.

extra:
  recipe-maintainers:
     - ekomarova
     - vtavana
     - xaleryb
