name: Build project with standard clang compiler

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build-with-standard-clang:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]

    env:
      COMPILER_ROOT: /usr/bin

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install mkl-service dependencies
        run: |
          pip install meson-python "cython>=3.1.0" cmake ninja mkl-devel

      - name: Build mkl-service
        run: |
          export CC=${{ env.COMPILER_ROOT }}/clang
          pip install -e ".[test]" --no-build-isolation --verbose
          pip list
          python -m pytest -v mkl/tests
