name: Build project with IntelLLVM clang compiler

on:
  push:
    branches:
      - master
  pull_request:

permissions: read-all

jobs:
  build-with-clang:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]  # 3.9 fails - gh-issue#56

    env:
      ONEAPI_ROOT: /opt/intel/oneapi

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Add Intel repository
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
          sudo apt-get update

      - name: Install Intel OneAPI
        run: |
          sudo apt-get install intel-oneapi-compiler-dpcpp-cpp
          sudo apt-get install intel-oneapi-tbb
          sudo apt-get install intel-oneapi-mkl-devel

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install mkl-service dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            cython
            setuptools>=77
            pytest

      - name: List oneAPI folder content
        run: ls ${{ env.ONEAPI_ROOT }}/compiler

      - name: Build mkl-service
        run: |
          source ${{ env.ONEAPI_ROOT }}/setvars.sh
          echo $CMPLR_ROOT
          export CC=$CMPLR_ROOT/bin/icx
          export CFLAGS="${CFLAGS} -fno-fast-math"
          python setup.py develop

      - name: Run mkl-service tests    
        run: |
          source ${{ env.ONEAPI_ROOT }}/setvars.sh
          pytest -s -v --pyargs mkl
