name: Conda package using Intel

on:
  push:
    branches:
      - master
  pull_request:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: linux
    uses: ./.github/workflows/conda-build-test.yml
    with:
      runs-on: ubuntu-latest
      conda-subdir: linux-64
      pkgs-dir: /home/runner/conda_pkgs_dir
      channels-list: -c https://software.repos.intel.com/python/conda -c conda-forge --override-channels
      recipe-dir: conda-recipe
      build-wheels: true

  windows:
    name: windows
    uses: ./.github/workflows/conda-build-test.yml
    with:
      runs-on: windows-latest
      conda-subdir: win-64
      pkgs-dir: D:\conda_pkgs_dir
      channels-list: -c https://software.repos.intel.com/python/conda -c conda-forge --override-channels
      recipe-dir: conda-recipe
      build-wheels: true
